version: '2.1'

services:
  web:
    image: "mysite:${VARIANT:-py3}"
    build:
      context: .
      dockerfile: "${VARIANT:-py3}.dockerfile"
    ports: ['8000']
    environment:
      SECRET_KEY: secret
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      DATABASE_URL: postgres://mysite:secret@db/mysite
      CELERY_BROKER_URL: amqp://mysite:secret@amqp:5672//mysite
      # Extra env variables to enable Celery in the Django container
      CELERY_APP: mysite
      CELERY_BEAT: '1'
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mysite
      POSTGRES_USER: mysite
      POSTGRES_PASSWORD: secret
  amqp:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: /mysite
      RABBITMQ_DEFAULT_USER: mysite
      RABBITMQ_DEFAULT_PASS: secret
