sudo: required
services:
  - docker
language: bash

env:
  - VARIANT=debian
  - VARIANT=alpine

# Update Docker Engine
before_install:
  - sudo apt-get update
  - sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-engine

before_script:
  - IMAGE_TAG="praekeltfoundation/django-bootstrap:$VARIANT"
  - DOCKERFILE="$VARIANT.dockerfile"
script:
  - docker build --tag "$IMAGE_TAG" --file "$DOCKERFILE" .
  - ./test.sh "$IMAGE_TAG"

after_script:
  - docker images
