version: '2.3'
services:
  # Gunicorn & Nginx
  gunicorn:
    image: "mysite:${VARIANT:-py3-pods}"
    build:
      context: example
      args:
        VARIANT: ${VARIANT:-py3-pods}
    volumes:
      - static:/app/static
      - media:/app/media
      - gunicorn:/var/run/gunicorn
    environment:
      SECRET_KEY: secret
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      DATABASE_URL: postgres://mysite:secret@postgresql/mysite
      CELERY_BROKER_URL: amqp://mysite:secret@rabbitmq:5672//mysite
  nginx:
    image: praekeltfoundation/django-bootstrap:nginx
    build:
      context: pods/nginx
    ports: ['80']
    volumes:
      - static:/usr/share/nginx/static
      - media:/usr/share/nginx/media
      - gunicorn:/var/run/gunicorn

  # Celery
  worker:
    extends:
      service: gunicorn
    command: [celery, worker]
  beat:
    extends:
      service: gunicorn
    command: [celery, beat]

  # Infrastructure
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mysite
      POSTGRES_USER: mysite
      POSTGRES_PASSWORD: secret
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: /mysite
      RABBITMQ_DEFAULT_USER: mysite
      RABBITMQ_DEFAULT_PASS: secret

volumes:
  static:
  media:
  gunicorn:
